### ISSUE TITLE
03.02.02

### ISSUE THREAD

**Issue by r-dean** [CMPUT301F23T03/BlackBox#30]
As an owner I want to be able to see some of the tags applied to an item when viewing it from a list.
Requirements/Prerequisites:
- US 03.02.01: there must already be functionality for adding tags to an item
- Tags should be displayed between the name of the item and its estimated value.
- If there are too many tags to display only display a few of them.

**Comment by pwthai** [comment]
Currently created an indicator whether an item has a tag or not, I believe this is a better implementation due to the fact that an item can have a large amount of tags, yet only would be shown.

**Comment by pwthai** [comment]
Test case finished, will decide in the future if the presentation is acceptable or not, otherwise reopen this user story.
